### PR TITLE
Add MySQL db

### PR DESCRIPTION
**Pull request by mathieupetersonGC**
#4

### CODE REVIEW

**Comment by JoChampagne-BACLAC** [comment]
#### Terraform Initialization : success`
#### Terraform Plan : success`
<details><summary>Show Plan</summary>

```

[0m[1mdata.aws_subnets.selected: Reading...[0m[0m
[0m[1maws_security_group.ga_app_sg: Refreshing state... [id=sg-0ad31ddb6190d00d9][0m
[0m[1maws_security_group.ga_lb_sg: Refreshing state... [id=sg-07549d1a50ac6911a][0m
[0m[1maws_security_group.ga_db_sg: Refreshing state... [id=sg-0435f60a17587de23][0m
[0m[1maws_security_group_rule.allow_internet: Refreshing state... [id=sgrule-3883739667][0m
[0m[1mdata.aws_subnets.selected: Read complete after 0s [id=ca-central-1][0m
[0m[1maws_db_subnet_group.data: Refreshing state... [id=ga-db-subnet-group][0m
[0m[1maws_security_group_rule.allow_tcp_3306: Refreshing state... [id=sgrule-2083674093][0m
[0m[1maws_security_group_rule.allow_tcp_443: Refreshing state... [id=sgrule-1590019062][0m

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  [32m+[0m create[0m

Terraform will perform the following actions:

[1m  # aws_db_instance.ga-mysql[0m will be created
[0m  [32m+[0m[0m resource "aws_db_instance" "ga-mysql" {
      [32m+[0m[0m address                               = (known after apply)
      [32m+[0m[0m allocated_storage                     = 20
      [32m+[0m[0m apply_immediately                     = false
      [32m+[0m[0m arn                                   = (known after apply)
      [32m+[0m[0m auto_minor_version_upgrade            = true
      [32m+[0m[0m availability_zone                     = (known after apply)
      [32m+[0m[0m backup_retention_period               = (known after apply)
      [32m+[0m[0m backup_target                         = (known after apply)
      [32m+[0m[0m backup_window                         = (known after apply)
      [32m+[0m[0m ca_cert_identifier                    = (known after apply)
      [32m+[0m[0m character_set_name                    = (known after apply)
      [32m+[0m[0m copy_tags_to_snapshot                 = false
      [32m+[0m[0m db_name                               = "gadbtest"
      [32m+[0m[0m db_subnet_group_name                  = "ga-db-subnet-group"
      [32m+[0m[0m delete_automated_backups              = true
      [32m+[0m[0m domain_fqdn                           = (known after apply)
      [32m+[0m[0m endpoint                              = (known after apply)
      [32m+[0m[0m engine                                = "mysql"
      [32m+[0m[0m engine_version                        = "8.0.35"
      [32m+[0m[0m engine_version_actual                 = (known after apply)
      [32m+[0m[0m hosted_zone_id                        = (known after apply)
      [32m+[0m[0m id                                    = (known after apply)
      [32m+[0m[0m identifier                            = (known after apply)
      [32m+[0m[0m identifier_prefix                     = (known after apply)
      [32m+[0m[0m instance_class                        = "db.t3.micro"
      [32m+[0m[0m iops                                  = (known after apply)
      [32m+[0m[0m kms_key_id                            = (known after apply)
      [32m+[0m[0m latest_restorable_time                = (known after apply)
      [32m+[0m[0m license_model                         = (known after apply)
      [32m+[0m[0m listener_endpoint                     = (known after apply)
      [32m+[0m[0m maintenance_window                    = (known after apply)
      [32m+[0m[0m master_user_secret                    = (known after apply)
      [32m+[0m[0m master_user_secret_kms_key_id         = (known after apply)
      [32m+[0m[0m monitoring_interval                   = 0
      [32m+[0m[0m monitoring_role_arn                   = (known after apply)
      [32m+[0m[0m multi_az                              = (known after apply)
      [32m+[0m[0m nchar_character_set_name              = (known after apply)
      [32m+[0m[0m network_type                          = (known after apply)
      [32m+[0m[0m option_group_name                     = (known after apply)
      [32m+[0m[0m parameter_group_name                  = "default.mysql8.0"
      [32m+[0m[0m password                              = (sensitive value)
      [32m+[0m[0m performance_insights_enabled          = false
      [32m+[0m[0m performance_insights_kms_key_id       = (known after apply)
      [32m+[0m[0m performance_insights_retention_period = (known after apply)
      [32m+[0m[0m port                                  = (known after apply)
      [32m+[0m[0m publicly_accessible                   = false
      [32m+[0m[0m replica_mode                          = (known after apply)
      [32m+[0m[0m replicas                              = (known after apply)
      [32m+[0m[0m resource_id                           = (known after apply)
      [32m+[0m[0m skip_final_snapshot                   = true
      [32m+[0m[0m snapshot_identifier                   = (known after apply)
      [32m+[0m[0m status                                = (known after apply)
      [32m+[0m[0m storage_encrypted                     = true
      [32m+[0m[0m storage_throughput                    = (known after apply)
      [32m+[0m[0m storage_type                          = (known after apply)
      [32m+[0m[0m tags_all                              = (known after apply)
      [32m+[0m[0m timezone                              = (known after apply)
      [32m+[0m[0m username                              = (sensitive value)
      [32m+[0m[0m vpc_security_group_ids                = [
          [32m+[0m[0m "sg-0435f60a17587de23",
        ]
    }

[1mPlan:[0m 1 to add, 0 to change, 0 to destroy.
[0m[90m
─────────────────────────────────────────────────────────────────────────────[0m

Note: You didn't use the -out option to save this plan, so Terraform can't
guarantee to take exactly these actions if you run "terraform apply" now.

```

</details>

*Pushed by: @mathieupetersonGC, Action: `pull_request`*

**Comment by JoChampagne-BACLAC** [comment]
#### Terraform Initialization : success`
#### Terraform Plan : success`
<details><summary>Show Plan</summary>

```

[0m[1mdata.aws_subnets.selected: Reading...[0m[0m
[0m[1maws_security_group.ga_db_sg: Refreshing state... [id=sg-0435f60a17587de23][0m
[0m[1maws_security_group.ga_app_sg: Refreshing state... [id=sg-0ad31ddb6190d00d9][0m
[0m[1maws_security_group.ga_lb_sg: Refreshing state... [id=sg-07549d1a50ac6911a][0m
[0m[1maws_security_group_rule.allow_tcp_443: Refreshing state... [id=sgrule-1590019062][0m
[0m[1maws_security_group_rule.allow_internet: Refreshing state... [id=sgrule-3883739667][0m
[0m[1maws_security_group_rule.allow_tcp_3306: Refreshing state... [id=sgrule-2083674093][0m
[0m[1mdata.aws_subnets.selected: Read complete after 0s [id=ca-central-1][0m
[0m[1maws_db_subnet_group.data: Refreshing state... [id=ga-db-subnet-group][0m

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  [32m+[0m create[0m

Terraform will perform the following actions:

[1m  # aws_db_instance.ga-mysql[0m will be created
[0m  [32m+[0m[0m resource "aws_db_instance" "ga-mysql" {
      [32m+[0m[0m address                               = (known after apply)
      [32m+[0m[0m allocated_storage                     = 20
      [32m+[0m[0m apply_immediately                     = false
      [32m+[0m[0m arn                                   = (known after apply)
      [32m+[0m[0m auto_minor_version_upgrade            = true
      [32m+[0m[0m availability_zone                     = (known after apply)
      [32m+[0m[0m backup_retention_period               = (known after apply)
      [32m+[0m[0m backup_target                         = (known after apply)
      [32m+[0m[0m backup_window                         = (known after apply)
      [32m+[0m[0m ca_cert_identifier                    = (known after apply)
      [32m+[0m[0m character_set_name                    = (known after apply)
      [32m+[0m[0m copy_tags_to_snapshot                 = false
      [32m+[0m[0m db_name                               = (sensitive value)
      [32m+[0m[0m db_subnet_group_name                  = "ga-db-subnet-group"
      [32m+[0m[0m delete_automated_backups              = true
      [32m+[0m[0m domain_fqdn                           = (known after apply)
      [32m+[0m[0m endpoint                              = (known after apply)
      [32m+[0m[0m engine                                = "mysql"
      [32m+[0m[0m engine_version                        = "8.0.35"
      [32m+[0m[0m engine_version_actual                 = (known after apply)
      [32m+[0m[0m hosted_zone_id                        = (known after apply)
      [32m+[0m[0m id                                    = (known after apply)
      [32m+[0m[0m identifier                            = (known after apply)
      [32m+[0m[0m identifier_prefix                     = (known after apply)
      [32m+[0m[0m instance_class                        = "db.t3.micro"
      [32m+[0m[0m iops                                  = (known after apply)
      [32m+[0m[0m kms_key_id                            = (known after apply)
      [32m+[0m[0m latest_restorable_time                = (known after apply)
      [32m+[0m[0m license_model                         = (known after apply)
      [32m+[0m[0m listener_endpoint                     = (known after apply)
      [32m+[0m[0m maintenance_window                    = (known after apply)
      [32m+[0m[0m master_user_secret                    = (known after apply)
      [32m+[0m[0m master_user_secret_kms_key_id         = (known after apply)
      [32m+[0m[0m monitoring_interval                   = 0
      [32m+[0m[0m monitoring_role_arn                   = (known after apply)
      [32m+[0m[0m multi_az                              = (known after apply)
      [32m+[0m[0m nchar_character_set_name              = (known after apply)
      [32m+[0m[0m network_type                          = (known after apply)
      [32m+[0m[0m option_group_name                     = (known after apply)
      [32m+[0m[0m parameter_group_name                  = "default.mysql8.0"
      [32m+[0m[0m password                              = (sensitive value)
      [32m+[0m[0m performance_insights_enabled          = false
      [32m+[0m[0m performance_insights_kms_key_id       = (known after apply)
      [32m+[0m[0m performance_insights_retention_period = (known after apply)
      [32m+[0m[0m port                                  = (known after apply)
      [32m+[0m[0m publicly_accessible                   = false
      [32m+[0m[0m replica_mode                          = (known after apply)
      [32m+[0m[0m replicas                              = (known after apply)
      [32m+[0m[0m resource_id                           = (known after apply)
      [32m+[0m[0m skip_final_snapshot                   = true
      [32m+[0m[0m snapshot_identifier                   = (known after apply)
      [32m+[0m[0m status                                = (known after apply)
      [32m+[0m[0m storage_encrypted                     = true
      [32m+[0m[0m storage_throughput                    = (known after apply)
      [32m+[0m[0m storage_type                          = (known after apply)
      [32m+[0m[0m tags_all                              = (known after apply)
      [32m+[0m[0m timezone                              = (known after apply)
      [32m+[0m[0m username                              = (sensitive value)
      [32m+[0m[0m vpc_security_group_ids                = [
          [32m+[0m[0m "sg-0435f60a17587de23",
        ]
    }

[1mPlan:[0m 1 to add, 0 to change, 0 to destroy.
[0m[90m
─────────────────────────────────────────────────────────────────────────────[0m

Note: You didn't use the -out option to save this plan, so Terraform can't
guarantee to take exactly these actions if you run "terraform apply" now.

```

</details>

*Pushed by: @mathieupetersonGC, Action: `pull_request`*

**Comment by JoChampagne-BACLAC** [comment]
#### Terraform Initialization : success`
#### Terraform Plan : success`
<details><summary>Show Plan</summary>

```

[0m[1mdata.aws_subnets.selected: Reading...[0m[0m
[0m[1maws_security_group.ga_app_sg: Refreshing state... [id=sg-0ad31ddb6190d00d9][0m
[0m[1maws_security_group.ga_db_sg: Refreshing state... [id=sg-0435f60a17587de23][0m
[0m[1maws_security_group.ga_lb_sg: Refreshing state... [id=sg-07549d1a50ac6911a][0m
[0m[1maws_security_group_rule.allow_tcp_3306: Refreshing state... [id=sgrule-2083674093][0m
[0m[1maws_security_group_rule.allow_internet: Refreshing state... [id=sgrule-3883739667][0m
[0m[1maws_security_group_rule.allow_tcp_443: Refreshing state... [id=sgrule-1590019062][0m
[0m[1mdata.aws_subnets.selected: Read complete after 0s [id=ca-central-1][0m
[0m[1maws_db_subnet_group.data: Refreshing state... [id=ga-db-subnet-group][0m
[0m[1maws_db_instance.ga-mysql: Refreshing state... [id=db-TN25BXY5XN5ULNKTAH7ZJW3PUE][0m

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
[31m-[0m/[32m+[0m destroy and then create replacement[0m

Terraform will perform the following actions:

[1m  # aws_db_instance.ga-mysql[0m must be [1m[31mreplaced[0m
[0m[31m-[0m/[32m+[0m[0m resource "aws_db_instance" "ga-mysql" {
      [33m~[0m[0m address                               = "terraform-20240517112630000400000001.cviyquy6eu7o.ca-central-1.rds.amazonaws.com" -> (known after apply)
      [33m~[0m[0m arn                                   = "arn:aws:rds:ca-central-1:654654488989:db:terraform-20240517112630000400000001" -> (known after apply)
      [33m~[0m[0m availability_zone                     = "ca-central-1a" -> (known after apply)
      [33m~[0m[0m backup_retention_period               = 0 -> (known after apply)
      [33m~[0m[0m backup_target                         = "region" -> (known after apply)
      [33m~[0m[0m backup_window                         = "08:42-09:12" -> (known after apply)
      [33m~[0m[0m ca_cert_identifier                    = "rds-ca-rsa2048-g1" -> (known after apply)
      [32m+[0m[0m character_set_name                    = (known after apply)
      [31m-[0m[0m customer_owned_ip_enabled             = false [90m-> null[0m[0m
      [33m~[0m[0m db_name                               = (sensitive value) [31m# forces replacement[0m[0m
      [31m-[0m[0m deletion_protection                   = false [90m-> null[0m[0m
      [31m-[0m[0m domain_dns_ips                        = [] [90m-> null[0m[0m
      [32m+[0m[0m domain_fqdn                           = (known after apply)
      [31m-[0m[0m enabled_cloudwatch_logs_exports       = [] [90m-> null[0m[0m
      [33m~[0m[0m endpoint                              = "terraform-20240517112630000400000001.cviyquy6eu7o.ca-central-1.rds.amazonaws.com:3306" -> (known after apply)
      [33m~[0m[0m engine_version_actual                 = "8.0.35" -> (known after apply)
      [33m~[0m[0m hosted_zone_id                        = "Z1JG78A3UK1DU3" -> (known after apply)
      [31m-[0m[0m iam_database_authentication_enabled   = false [90m-> null[0m[0m
      [33m~[0m[0m id                                    = "db-TN25BXY5XN5ULNKTAH7ZJW3PUE" -> (known after apply)
      [33m~[0m[0m identifier                            = "terraform-20240517112630000400000001" -> (known after apply)
      [33m~[0m[0m identifier_prefix                     = "terraform-" -> (known after apply)
      [33m~[0m[0m iops                                  = 0 -> (known after apply)
      [33m~[0m[0m kms_key_id                            = "arn:aws:kms:ca-central-1:654654488989:key/4230c728-a472-47cc-bce4-1e09c23ffd0f" -> (known after apply)
      [32m+[0m[0m latest_restorable_time                = (known after apply)
      [33m~[0m[0m license_model                         = "general-public-license" -> (known after apply)
      [33m~[0m[0m listener_endpoint                     = [] -> (known after apply)
      [33m~[0m[0m maintenance_window                    = "wed:07:30-wed:08:00" -> (known after apply)
      [33m~[0m[0m master_user_secret                    = [] -> (known after apply)
      [32m+[0m[0m master_user_secret_kms_key_id         = (known after apply)
      [31m-[0m[0m max_allocated_storage                 = 0 [90m-> null[0m[0m
      [32m+[0m[0m monitoring_role_arn                   = (known after apply)
      [33m~[0m[0m multi_az                              = false -> (known after apply)
      [32m+[0m[0m nchar_character_set_name              = (known after apply)
      [33m~[0m[0m network_type                          = "IPV4" -> (known after apply)
      [33m~[0m[0m option_group_name                     = "default:mysql-8-0" -> (known after apply)
      [32m+[0m[0m performance_insights_kms_key_id       = (known after apply)
      [33m~[0m[0m performance_insights_retention_period = 0 -> (known after apply)
      [33m~[0m[0m port                                  = 3306 -> (known after apply)
      [32m+[0m[0m replica_mode                          = (known after apply)
      [33m~[0m[0m replicas                              = [] -> (known after apply)
      [33m~[0m[0m resource_id                           = "db-TN25BXY5XN5ULNKTAH7ZJW3PUE" -> (known after apply)
      [32m+[0m[0m snapshot_identifier                   = (known after apply)
      [33m~[0m[0m status                                = "available" -> (known after apply)
      [33m~[0m[0m storage_throughput                    = 0 -> (known after apply)
      [33m~[0m[0m storage_type                          = "gp2" -> (known after apply)
      [31m-[0m[0m tags                                  = {} [90m-> null[0m[0m
      [33m~[0m[0m tags_all                              = {} -> (known after apply)
      [32m+[0m[0m timezone                              = (known after apply)
        [90m# (24 unchanged attributes hidden)[0m[0m
    }

[1mPlan:[0m 1 to add, 0 to change, 1 to destroy.
[0m[90m
─────────────────────────────────────────────────────────────────────────────[0m

Note: You didn't use the -out option to save this plan, so Terraform can't
guarantee to take exactly these actions if you run "terraform apply" now.

```

</details>

*Pushed by: @mathieupetersonGC, Action: `pull_request`*

**Comment by JoChampagne-BACLAC** [comment]
#### Terraform Initialization : success`
#### Terraform Plan : success`
<details><summary>Show Plan</summary>

```

[0m[1maws_security_group.ga_app_sg: Refreshing state... [id=sg-0ad31ddb6190d00d9][0m
[0m[1maws_security_group.ga_lb_sg: Refreshing state... [id=sg-07549d1a50ac6911a][0m
[0m[1maws_security_group.ga_db_sg: Refreshing state... [id=sg-0435f60a17587de23][0m
[0m[1maws_db_instance.ga-mysql: Refreshing state... [id=db-6F2RNQSVA34K4YTZER3IKDAIN4][0m
[0m[1mdata.aws_subnets.selected: Reading...[0m[0m
[0m[1maws_security_group_rule.allow_tcp_3306: Refreshing state... [id=sgrule-2083674093][0m
[0m[1maws_security_group_rule.allow_tcp_443: Refreshing state... [id=sgrule-1590019062][0m
[0m[1maws_security_group_rule.allow_internet: Refreshing state... [id=sgrule-3883739667][0m
[0m[1mdata.aws_subnets.selected: Read complete after 0s [id=ca-central-1][0m
[0m[1maws_db_subnet_group.data: Refreshing state... [id=ga-db-subnet-group][0m

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  [32m+[0m create[0m
  [31m-[0m destroy[0m

Terraform will perform the following actions:

[1m  # aws_db_instance.ga-mysql[0m will be [1m[31mdestroyed[0m
  # (because aws_db_instance.ga-mysql is not in configuration)
[0m  [31m-[0m[0m resource "aws_db_instance" "ga-mysql" {
      [31m-[0m[0m address                               = "terraform-20240517114620093700000001.cviyquy6eu7o.ca-central-1.rds.amazonaws.com" [90m-> null[0m[0m
      [31m-[0m[0m allocated_storage                     = 20 [90m-> null[0m[0m
      [31m-[0m[0m apply_immediately                     = false [90m-> null[0m[0m
      [31m-[0m[0m arn                                   = "arn:aws:rds:ca-central-1:654654488989:db:terraform-20240517114620093700000001" [90m-> null[0m[0m
      [31m-[0m[0m auto_minor_version_upgrade            = true [90m-> null[0m[0m
      [31m-[0m[0m availability_zone                     = "ca-central-1a" [90m-> null[0m[0m
      [31m-[0m[0m backup_retention_period               = 0 [90m-> null[0m[0m
      [31m-[0m[0m backup_target                         = "region" [90m-> null[0m[0m
      [31m-[0m[0m backup_window                         = "03:16-03:46" [90m-> null[0m[0m
      [31m-[0m[0m ca_cert_identifier                    = "rds-ca-rsa2048-g1" [90m-> null[0m[0m
      [31m-[0m[0m copy_tags_to_snapshot                 = false [90m-> null[0m[0m
      [31m-[0m[0m customer_owned_ip_enabled             = false [90m-> null[0m[0m
      [31m-[0m[0m db_name                               = (sensitive value) [90m-> null[0m[0m
      [31m-[0m[0m db_subnet_group_name                  = "ga-db-subnet-group" [90m-> null[0m[0m
      [31m-[0m[0m delete_automated_backups              = true [90m-> null[0m[0m
      [31m-[0m[0m deletion_protection                   = false [90m-> null[0m[0m
      [31m-[0m[0m domain_dns_ips                        = [] [90m-> null[0m[0m
      [31m-[0m[0m enabled_cloudwatch_logs_exports       = [] [90m-> null[0m[0m
      [31m-[0m[0m endpoint                              = "terraform-20240517114620093700000001.cviyquy6eu7o.ca-central-1.rds.amazonaws.com:3306" [90m-> null[0m[0m
      [31m-[0m[0m engine                                = "mysql" [90m-> null[0m[0m
      [31m-[0m[0m engine_version                        = "8.0.35" [90m-> null[0m[0m
      [31m-[0m[0m engine_version_actual                 = "8.0.35" [90m-> null[0m[0m
      [31m-[0m[0m hosted_zone_id                        = "Z1JG78A3UK1DU3" [90m-> null[0m[0m
      [31m-[0m[0m iam_database_authentication_enabled   = false [90m-> null[0m[0m
      [31m-[0m[0m id                                    = "db-6F2RNQSVA34K4YTZER3IKDAIN4" [90m-> null[0m[0m
      [31m-[0m[0m identifier                            = "terraform-20240517114620093700000001" [90m-> null[0m[0m
      [31m-[0m[0m identifier_prefix                     = "terraform-" [90m-> null[0m[0m
      [31m-[0m[0m instance_class                        = "db.t3.micro" [90m-> null[0m[0m
      [31m-[0m[0m iops                                  = 0 [90m-> null[0m[0m
      [31m-[0m[0m kms_key_id                            = "arn:aws:kms:ca-central-1:654654488989:key/4230c728-a472-47cc-bce4-1e09c23ffd0f" [90m-> null[0m[0m
      [31m-[0m[0m license_model                         = "general-public-license" [90m-> null[0m[0m
      [31m-[0m[0m listener_endpoint                     = [] [90m-> null[0m[0m
      [31m-[0m[0m maintenance_window                    = "fri:06:46-fri:07:16" [90m-> null[0m[0m
      [31m-[0m[0m master_user_secret                    = [] [90m-> null[0m[0m
      [31m-[0m[0m max_allocated_storage                 = 0 [90m-> null[0m[0m
      [31m-[0m[0m monitoring_interval                   = 0 [90m-> null[0m[0m
      [31m-[0m[0m multi_az                              = false [90m-> null[0m[0m
      [31m-[0m[0m network_type                          = "IPV4" [90m-> null[0m[0m
      [31m-[0m[0m option_group_name                     = "default:mysql-8-0" [90m-> null[0m[0m
      [31m-[0m[0m parameter_group_name                  = "default.mysql8.0" [90m-> null[0m[0m
      [31m-[0m[0m password                              = (sensitive value) [90m-> null[0m[0m
      [31m-[0m[0m performance_insights_enabled          = false [90m-> null[0m[0m
      [31m-[0m[0m performance_insights_retention_period = 0 [90m-> null[0m[0m
      [31m-[0m[0m port                                  = 3306 [90m-> null[0m[0m
      [31m-[0m[0m publicly_accessible                   = false [90m-> null[0m[0m
      [31m-[0m[0m replicas                              = [] [90m-> null[0m[0m
      [31m-[0m[0m resource_id                           = "db-6F2RNQSVA34K4YTZER3IKDAIN4" [90m-> null[0m[0m
      [31m-[0m[0m skip_final_snapshot                   = true [90m-> null[0m[0m
      [31m-[0m[0m status                                = "available" [90m-> null[0m[0m
      [31m-[0m[0m storage_encrypted                     = true [90m-> null[0m[0m
      [31m-[0m[0m storage_throughput                    = 0 [90m-> null[0m[0m
      [31m-[0m[0m storage_type                          = "gp2" [90m-> null[0m[0m
      [31m-[0m[0m tags                                  = {} [90m-> null[0m[0m
      [31m-[0m[0m tags_all                              = {} [90m-> null[0m[0m
      [31m-[0m[0m username                              = (sensitive value) [90m-> null[0m[0m
      [31m-[0m[0m vpc_security_group_ids                = [
          [31m-[0m[0m "sg-0435f60a17587de23",
        ] [90m-> null[0m[0m
        [90m# (14 unchanged attributes hidden)[0m[0m
    }

[1m  # aws_db_instance.ga_mysql[0m will be created
[0m  [32m+[0m[0m resource "aws_db_instance" "ga_mysql" {
      [32m+[0m[0m address                               = (known after apply)
      [32m+[0m[0m allocated_storage                     = 20
      [32m+[0m[0m apply_immediately                     = false
      [32m+[0m[0m arn                                   = (known after apply)
      [32m+[0m[0m auto_minor_version_upgrade            = true
      [32m+[0m[0m availability_zone                     = (known after apply)
      [32m+[0m[0m backup_retention_period               = (known after apply)
      [32m+[0m[0m backup_target                         = (known after apply)
      [32m+[0m[0m backup_window                         = (known after apply)
      [32m+[0m[0m ca_cert_identifier                    = (known after apply)
      [32m+[0m[0m character_set_name                    = (known after apply)
      [32m+[0m[0m copy_tags_to_snapshot                 = false
      [32m+[0m[0m db_name                               = (sensitive value)
      [32m+[0m[0m db_subnet_group_name                  = "ga-db-subnet-group"
      [32m+[0m[0m delete_automated_backups              = true
      [32m+[0m[0m domain_fqdn                           = (known after apply)
      [32m+[0m[0m endpoint                              = (known after apply)
      [32m+[0m[0m engine                                = "mysql"
      [32m+[0m[0m engine_version                        = "8.0.35"
      [32m+[0m[0m engine_version_actual                 = (known after apply)
      [32m+[0m[0m hosted_zone_id                        = (known after apply)
      [32m+[0m[0m id                                    = (known after apply)
      [32m+[0m[0m identifier                            = (known after apply)
      [32m+[0m[0m identifier_prefix                     = (known after apply)
      [32m+[0m[0m instance_class                        = "db.t3.micro"
      [32m+[0m[0m iops                                  = (known after apply)
      [32m+[0m[0m kms_key_id                            = (known after apply)
      [32m+[0m[0m latest_restorable_time                = (known after apply)
      [32m+[0m[0m license_model                         = (known after apply)
      [32m+[0m[0m listener_endpoint                     = (known after apply)
      [32m+[0m[0m maintenance_window                    = (known after apply)
      [32m+[0m[0m master_user_secret                    = (known after apply)
      [32m+[0m[0m master_user_secret_kms_key_id         = (known after apply)
      [32m+[0m[0m monitoring_interval                   = 0
      [32m+[0m[0m monitoring_role_arn                   = (known after apply)
      [32m+[0m[0m multi_az                              = (known after apply)
      [32m+[0m[0m nchar_character_set_name              = (known after apply)
      [32m+[0m[0m network_type                          = (known after apply)
      [32m+[0m[0m option_group_name                     = (known after apply)
      [32m+[0m[0m parameter_group_name                  = "default.mysql8.0"
      [32m+[0m[0m password                              = (sensitive value)
      [32m+[0m[0m performance_insights_enabled          = false
      [32m+[0m[0m performance_insights_kms_key_id       = (known after apply)
      [32m+[0m[0m performance_insights_retention_period = (known after apply)
      [32m+[0m[0m port                                  = (known after apply)
      [32m+[0m[0m publicly_accessible                   = false
      [32m+[0m[0m replica_mode                          = (known after apply)
      [32m+[0m[0m replicas                              = (known after apply)
      [32m+[0m[0m resource_id                           = (known after apply)
      [32m+[0m[0m skip_final_snapshot                   = true
      [32m+[0m[0m snapshot_identifier                   = (known after apply)
      [32m+[0m[0m status                                = (known after apply)
      [32m+[0m[0m storage_encrypted                     = true
      [32m+[0m[0m storage_throughput                    = (known after apply)
      [32m+[0m[0m storage_type                          = (known after apply)
      [32m+[0m[0m tags_all                              = (known after apply)
      [32m+[0m[0m timezone                              = (known after apply)
      [32m+[0m[0m username                              = (sensitive value)
      [32m+[0m[0m vpc_security_group_ids                = [
          [32m+[0m[0m "sg-0435f60a17587de23",
        ]
    }

[1mPlan:[0m 1 to add, 0 to change, 1 to destroy.
[0m[90m
─────────────────────────────────────────────────────────────────────────────[0m

Note: You didn't use the -out option to save this plan, so Terraform can't
guarantee to take exactly these actions if you run "terraform apply" now.

```

</details>

*Pushed by: @mathieupetersonGC, Action: `pull_request`*

**Review by JoChampagne-BACLAC — APPROVED** [review]

**Review by cedricguindon — APPROVED** [review]

**Pull request merged**
